name: Android Store CI
on: 
  workflow_dispatch:
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
    - run: |
      flutter pub get
      flutter build apk --debug
