# Enable all rules by default
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore
    specify_nonobvious_property_types: ignore
    public_member_api_docs: ignore
    omit_local_variable_types: ignore
    lines_longer_than_80_chars: ignore
    use_setters_to_change_properties: ignore
    flutter_style_todos: ignore
  exclude:
    - '**/lib/**/*.freezed.dart'
    - '**/lib/**/*.g.dart'
    - '**/i18n/*'
    - 'ci/**'
    - 'coverage/**'
    - 'third_parties/**'
    - 'submodules/**'

linter:
  rules:
    cancel_subscriptions
    close_sinks
    avoid_bool_literals_in_conditional_expressions
    prefer_const_constructors
    prefer_const_declarations
    prefer_const_literals_to_create_immutables
    prefer_final_in_for_each
    prefer_final_locals
    prefer_null_aware_method_calls
    sized_box_shrink_expand
    throw_in_finally
    unnecessary_lambdas
    use_decorated_box
    use_colored_box
    use_null_aware_elements
    use_string_buffers