# Enable all rules by default
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore
  exclude:
    - '**/lib/**/*.freezed.dart'
    - '**/lib/**/*.g.dart'
    - '**/i18n/*'
    - 'ci/**'
    - 'coverage/**'
    - 'third_parties/**'
    - 'submodules/**'

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    use_setters_to_change_properties: false
