# Enable all rules by default
include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    dead_code: warning
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # The conflicts are fixed in this file instead, so we can safely ignore the warning.
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    await_only_futures: error
  exclude:
    - '**/lib/**/*.freezed.dart'
    - '**/lib/**/*.g.dart'
    - '**/i18n/*'
    - 'ci/**'
    - 'coverage/**'
    - 'third_parties/**'
    - 'submodules/**'

linter:
  rules:
