name: snow_weather_info
description: A application to display french snow weather beacon informations
publish_to: none

version: 2.3.0+34

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: any
  csv: ^6.0.0
  dart_rss:
    git:
      url: https://github.com/Chonli/webfeed.git
      ref: feature/geo-rss-2
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.2.1
  flutter_map_marker_cluster: ^1.3.4
  flutter_sticky_header: ^0.6.5
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: any
  json_annotation: ^4.9.0
  latlong2: ^0.9.0
  location: ^7.0.0
  logging: ^1.2.0
  package_info: ^2.0.2
  path: ^1.9.0
  pdfx: ^2.6.0
  riverpod_annotation: ^2.3.4
  share: ^2.0.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  build_runner_core: ^7.3.0
  custom_lint: ^0.6.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.11
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/test_data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
