name: snow_weather_info
description: A application to display french snow weather beacon informations
publish_to: none

version: 1.9.0+24

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  provider: ^6.0.3
  http: ^0.13.4
  latlong2: ^0.8.1
  csv: ^5.0.1
  intl: ^0.17.0
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.4
  # user_location: ^0.1.3
  charts_flutter: ^0.12.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  package_info: ^2.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  share: ^2.0.4
  azlistview: ^2.0.0
  webview_flutter: ^3.0.4
  flutter_sticky_header: ^0.6.3
  logging: ^1.0.2
  dart_rss:
    git:
      url: https://github.com/Chonli/webfeed.git
      ref: feature/geo-rss-2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/test_data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
