name: snow_weather_info
description: A application to display french snow weather beacon informations
publish_to: none

version: 1.10.2+27

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: any
  flutter_launcher_icons: ^0.13.1
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  http: ^1.1.0
  latlong2: ^0.9.0
  csv: ^5.1.1
  intl: ^0.18.0
  flutter_map: ^6.0.1
  flutter_map_marker_cluster: ^1.3.3
  fl_chart: ^0.65.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  package_info: ^2.0.2
  share: ^2.0.4
  webview_flutter: ^3.0.4
  flutter_sticky_header: ^0.6.5
  smooth_page_indicator: ^1.1.0
  location: ^5.0.3
  logging: ^1.2.0
  dart_rss:
    git:
      url: https://github.com/Chonli/webfeed.git
      ref: feature/geo-rss-2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.6
  build_runner: any
  build_runner_core: ^7.2.9
  riverpod_generator: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/test_data/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
