name: snow_weather_info
description: A application to display french snow weather beacon informations
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.9.0"
  provider: ^4.3.2+1
  http: ^0.12.0+4
  latlong: ^0.6.1
  csv: ^4.1.0
  intl: ^0.17.0
  flutter_map: ^0.12.0
  charts_flutter: ^0.10.0
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.7.10
  location: ^3.0.2
  package_info: ^0.4.3
  native_pdf_view: ^4.0.1
  carousel_slider: ^3.0.0
  share: ^0.6.4+5
  sticky_headers: ^0.1.8+1
  alphabet_list_scroll_view: ^1.0.6
  webfeed:
    git:
      url: https://github.com/Chonli/webfeed.git
      ref: develop


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
