name: snow_weather_info
description: A application to display french snow weather beacon informations
publish_to: none

version: 2.1.1+31

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: any
  csv: ^5.1.1
  dart_rss:
    git:
      url: https://github.com/Chonli/webfeed.git
      ref: feature/geo-rss-2
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.0.1
  flutter_map_marker_cluster: ^1.3.3
  flutter_sticky_header: ^0.6.5
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.6
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  location: ^5.0.3
  logging: ^1.2.0
  package_info: ^2.0.2
  path: ^1.8.3
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter
      ref: 8b105a7dfc6b90220c1d79fcb805fb764cab00c5
      path: packages/pdfx
  riverpod_annotation: ^2.3.1
  share: ^2.0.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  build_runner_core: ^7.2.9
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/test_data/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
